### ISSUE TITLE
In- and Outputs of Processes not matchable in RDF graph

### ISSUE THREAD

**Issue by feserm** [nfdi4plants/ARC-specfication#129]
_Not sure, if this is the right place. Feel free to move this issue._

When loading the ro-crate-metadata.json into a RDF Graph to query using SPARQL. I can't connect Sources to Samples. This is because, the RO-Crate has one Process with n inputs and n outputs, **expecting** those to be well-ordered. However, the graph loads those inputs and outputs in an unordered manner.  So there is no way for me of matching inputs to outputs.

One way to fix this issue would be to put n processes into the processSequence, each having one input and one output. That way it would be feasible to match Sources and Samples, regardless of order. Otherwise an additionalProperty "derivedFrom" or similar could also solve this issue.

Maybe I'm overlooking something. Otherwise, I'm curious to hear your opinions on this.

**Comment by HLWeil** [comment]
Hey @feserm,

thanks for your input. This is something I also just noticed and opened an [Issue in ARCtrl](https://github.com/nfdi4plants/ARCtrl/issues/475). 

In JSON-LD, ordering of elements is usually ignored. This will be accounted for in the next bigger release of ARCtrl. 

I will close this issue here now, as the one in ARCtrl is already opened and in the correct Repo.
