### ISSUE TITLE
directory for additional payload

### ISSUE THREAD

**Issue by johanneswerner** [nfdi4plants/ARC-specfication#43]
In the section additional payload

> While these files can be placed anywhere in the ARC, it is strongly advised to organize these in additional subdirectories.

I would add in the specification a dedicated directory where these files SHOULD reside.

**Comment by cgarth** [comment]
It must be possible to place AP files anywhere in an ARC, so that an ARC can simultaneously be an RO Crate for example – this requires `ro-crate-metadata.json` in the top-level directory. Furthermore, users should be free to add files such as README.txt or other annotations in workflows or runs (or anywhere, really).

Fundamentally, everything in an ARC is AP unless it is linked from top-level metadata (ie. from arc.cwl / isa.investigation.xlsx).
